---
extends: existence
message: Using '%s' may come across as condescending.
link: https://css-tricks.com/words-avoid-educational-writing/
level: error
ignorecase: true
tokens:
  - obvious
  - obviously
  - easy
  - easily
  - of course
  - clearly
  - everyone knows
